

import Path from 'node:path'
import * as Fs from 'node:fs'

import { test, describe, afterEach } from 'node:test'
import assert from 'node:assert'
import { createLiveTransport } from '../../live-runner'
import { runLiveEntity } from '../../live-entity'


import { DigitaloceanSDK, BaseFeature, config, stdutil } from '../../..'

import {
  envOverride,
  liveClientOptions,
  liveDelay,
  loadEnvLocal,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
  maybeSkipControl,
} from '../../utility'


loadEnvLocal(__dirname + '/../../../.env.local')


describe('CreateResponseEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when DIGITALOCEAN_TEST_LIVE=TRUE.
  afterEach(liveDelay('DIGITALOCEAN_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = DigitaloceanSDK.test()
    const ent = testsdk.CreateResponse()
    assert(null != ent)
  })


  test('validate', async (t) => {
    if (null == (config as any).feature?.validate) {
      t.skip('feature not present in this SDK: validate')
      return
    }
    const client = DigitaloceanSDK.test(undefined, { feature: { validate: { active: true } } })
    await assert.rejects(client.CreateResponse().create({"created":"x","id":"x","input":"x","model":"x","object":"x","output":"x","usage":"x"} as any),
      (err: any) => 'validate_failed' === err.code)
  })



  test('basic', async (t) => {

    const live = 'TRUE' === process.env.DIGITALOCEAN_TEST_LIVE
    for (const op of ['create']) {
      if (!live && maybeSkipControl(t, 'entityOp', 'create_response.' + op, live)) return
    }

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":{"created":{"a":true,"h":"Created","n":"created","r":true,"sh":"The Unix timestamp (in seconds) of when the response was created.","t":"`$INTEGER`","key$":"created","index$":0},"id":{"a":true,"h":"Id","n":"id","r":true,"sh":"A unique identifier for the response.","t":"`$STRING`","key$":"id","index$":1},"input":{"a":true,"h":"Input","n":"input","r":true,"sh":"The prompt or input content you want the model to respond to.","t":"`$ANY`","union":{"branches":2,"count":1,"depth":0},"key$":"input","index$":2},"instructions":{"a":true,"h":"Instructions","n":"instructions","r":false,"sh":"System-level instructions for the model.","t":"`$STRING`","key$":"instructions","index$":3},"max_output_tokens":{"a":true,"h":"Max Output Tokens","n":"max_output_tokens","r":false,"sh":"Maximum output tokens setting.","t":"`$INTEGER`","key$":"max_output_tokens","index$":4},"metadata":{"a":true,"h":"Metadata","n":"metadata","r":false,"sh":"Set of key-value pairs that can be attached to the request.","t":"`$OBJECT`","key$":"metadata","index$":5},"model":{"a":true,"h":"Model","n":"model","r":true,"sh":"The model used to generate the response.","t":"`$STRING`","key$":"model","index$":6},"object":{"a":true,"h":"Object","n":"object","r":true,"sh":"The object type, which is always `response`.","t":"`$STRING`","key$":"object","index$":7},"output":{"a":true,"h":"Output","n":"output","r":true,"sh":"An array of content items generated by the model.","t":"`$ARRAY`","key$":"output","index$":8},"parallel_tool_calls":{"a":true,"h":"Parallel Tool Calls","n":"parallel_tool_calls","r":false,"sh":"Whether parallel tool calls are enabled.","t":"`$BOOLEAN`","key$":"parallel_tool_calls","index$":9},"status":{"a":true,"h":"Status","n":"status","r":false,"sh":"Status of the response.","t":"`$STRING`","key$":"status","index$":10},"stop":{"a":true,"h":"Stop","n":"stop","r":false,"sh":"Up to 4 sequences where the API will stop generating further tokens.","t":"`$ANY`","union":{"branches":2,"count":1,"depth":0},"key$":"stop","index$":11},"stream":{"a":true,"h":"Stream","n":"stream","r":false,"sh":"Set to true to stream partial responses as Server-Sent Events.","t":"`$BOOLEAN`","key$":"stream","index$":12},"stream_options":{"a":true,"h":"Stream Options","n":"stream_options","r":false,"sh":"Options for streaming response.","t":"`$OBJECT`","key$":"stream_options","index$":13},"temperature":{"a":true,"h":"Temperature","n":"temperature","r":false,"sh":"Temperature setting used for the response.","t":"`$NUMBER`","key$":"temperature","index$":14},"tool_choice":{"a":true,"h":"Tool Choice","n":"tool_choice","r":false,"sh":"Tool choice setting used for the response.","t":"`$STRING`","key$":"tool_choice","index$":15},"tools":{"a":true,"h":"Tools","n":"tools","r":false,"sh":"Tools available for the response.","t":"`$ARRAY`","key$":"tools","index$":16},"top_p":{"a":true,"h":"Top P","n":"top_p","r":false,"sh":"Top-p setting used for the response.","t":"`$NUMBER`","key$":"top_p","index$":17},"usage":{"a":true,"h":"Usage","n":"usage","r":true,"sh":"Detailed usage statistics for the Responses API request, including input/output token counts and detailed breakdowns.","t":"`$OBJECT`","key$":"usage","index$":18},"user":{"a":true,"h":"User","n":"user","r":false,"sh":"User identifier.","t":"`$STRING`","key$":"user","index$":19}},"id":{"field":"id","name":"id"},"name":"create_response","op":{"create":{"input":"data","name":"create","points":[{"a":true,"co":{"id":"POST /v1/responses","source":"openapi3","version":2},"g":{},"k":"http","m":"POST","o":"/v1/responses","q":{},"r":{},"rs":{"alternatives":[{"kind":"raw","media":"text/event-stream"}],"kind":"json","media":"application/json"},"s":[{"lit":"v1"},{"lit":"responses"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"create"}},"relations":{"ancestors":[]},"key$":"create_response","name__orig":"create_response","Name":"CreateResponse","name_":"create_response","name-":"create-response","NAME":"CREATE_RESPONSE","index$":135}, {"active":true,"entity":"create_response","key$":"BasicCreateResponseFlow","kind":"basic","name":"BasicCreateResponseFlow","param":{},"step":[{"a":true,"d":{},"i":{"ref":"create_response_ref01"},"m":{},"o":"create","s":[],"v":[],"index$":0}]}, 'CreateResponse', {"POST /v1/responses":{"protocol":"http","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","description":"Request body for sending a prompt to a model using the Responses API.","required":["model","input"],"properties":{"model":{"type":"string","description":"The model ID of the model you want to use. Get the model ID using `/v1/models` or on the available models page.\n","example":"openai-gpt-oss-20b","key$":"model"},"input":{"description":"The prompt or input content you want the model to respond to. Can be a simple text string or an array of message objects for conversation context.\n","oneOf":[{"type":"string","description":"Simple text input prompt.","example":"What is the capital of France?"},{"type":"array","description":"Array of message objects for conversation context.","minItems":1,"items":{"type":"object","properties":{},"required":[]}}],"key$":"input"},"max_output_tokens":{"type":"integer","minimum":1,"nullable":true,"description":"The maximum number of tokens to generate in the response.\n","example":50,"key$":"max_output_tokens"},"temperature":{"type":"number","minimum":0,"maximum":2,"nullable":true,"description":"A value between 0.0 and 2.0 to control randomness and creativity. Lower values like 0.2 make the output more focused and deterministic, while higher values like 0.8 make it more random.\n","example":0.7,"key$":"temperature"},"stream":{"type":"boolean","nullable":true,"default":false,"description":"Set to true to stream partial responses as Server-Sent Events.\n","example":false,"key$":"stream"},"instructions":{"type":"string","nullable":true,"description":"System-level instructions for the model. This sets the behavior and context for the response generation.\n","example":"You are a helpful assistant.","key$":"instructions"},"top_p":{"type":"number","minimum":0,"maximum":1,"nullable":true,"description":"An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass.\n","example":1,"key$":"top_p"},"stream_options":{"type":"object","nullable":true,"default":null,"description":"Options for streaming response. Only set this when you set stream to true.","properties":{"include_usage":{"type":"boolean","description":"If set, an additional chunk will be streamed before the data: [DONE] message with token usage statistics for the entire request.\n","example":true}},"key$":"stream_options"},"tools":{"type":"array","nullable":true,"description":"A list of tools the model may call.\n","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":[],"description":"The type of the tool.","example":"function"},"name":{"type":"string","description":"The name of the function to be called.","example":"get_weather"},"description":{"type":"string","description":"A description of what the function does.","example":"Get the current weather in a given location."},"parameters":{"type":"object","description":"The parameters the function accepts, described as a JSON Schema object.","additionalProperties":true}}},"key$":"tools"},"tool_choice":{"description":"Controls which (if any) tool is called by the model.\n","oneOf":[{"type":"string","enum":["none","auto","required"],"example":"auto"},{"type":"object","properties":{"type":{},"function":{}},"required":["type","function"]}],"key$":"tool_choice"},"stop":{"description":"Up to 4 sequences where the API will stop generating further tokens.\n","nullable":true,"default":null,"oneOf":[{"type":"string","example":"\n"},{"type":"array","minItems":1,"maxItems":4,"items":{"type":"string"}}],"key$":"stop"},"metadata":{"type":"object","nullable":true,"description":"Set of key-value pairs that can be attached to the request.\n","additionalProperties":{"type":"string"},"example":{"session_id":"abc123"},"key$":"metadata"},"user":{"type":"string","nullable":true,"description":"A unique identifier representing your end-user.\n","example":"user-1234","key$":"user"}},"x-ref":"#/components/schemas/create_response_request","index$":1}}}},"parameters":[]}}, { strict: LIVE_STRICT, t })
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const create_response_ref01_ent = client.CreateResponse()
    let create_response_ref01_data = setup.data.new.create_response['create_response_ref01']

    create_response_ref01_data = (await create_response_ref01_ent.create(create_response_ref01_data)).data()
    assert(null != create_response_ref01_data.id)


  })
})



// main.kit.test.live.strict is true (the default is true): a live
// request that fails, or a live test missing an input it needs,
// fails the test.
// An account with no record for a test to read skips it either way.
const LIVE_STRICT = true

function basicSetup(extra?: any) {
  // TODO: fix test def options
  const options: any = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname, 
      '../../../../.sdk/test/entity/create_response/CreateResponseTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = DigitaloceanSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['create_response01','create_response02','create_response03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'DIGITALOCEAN_TEST_CREATE_RESPONSE_ENTID': idmap,
    'DIGITALOCEAN_TEST_LIVE': 'FALSE',
    'DIGITALOCEAN_TEST_EXPLAIN': 'FALSE',
    'DIGITALOCEAN_APIKEY': '',
  })

  idmap = env['DIGITALOCEAN_TEST_CREATE_RESPONSE_ENTID']

  const live = 'TRUE' === env.DIGITALOCEAN_TEST_LIVE

  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['DIGITALOCEAN_TEST_CREATE_RESPONSE_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new DigitaloceanSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.DIGITALOCEAN_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
      // last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey
      // and server values above and handed the SDK undefined. Harmless
      // while there was nothing in that object; not harmless now.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.DIGITALOCEAN_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
